name: Hourly Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: production
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run scraper (with auto-healing)
        run: pnpm scrape https://www.property24.com/to-rent/walmer-estate/cape-town/western-cape/10163 --heal
        
      - name: Commit changes if any (from self-healing)
        if: success()
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "auto-heal: fix selector drift detected in hourly scrape"
            git push
          else
            echo "No changes to commit"
          fi